import Wrapper from "../../assets/wrappers/CommentsDisplay";

const CommentsDisplay = () => {
	return (
		<Wrapper>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
			<div>CommentsDisplay</div>
		</Wrapper>
	);
};

export default CommentsDisplay;
